// src/app/login/page.tsx
"use client";

import { getProviders, signIn } from "next-auth/react";

type PageProps = {
  providers: Record<string, string>[];
};

const Page = (props: PageProps) => {
  return (
    <div className="flex  min-h-screen w-full items-center justify-center">
      <div className="flex flex-col rounded-3xl">
        <button
          onClick={() => signIn("google")}
          className="flex items-center justify-between rounded-full border border-solid border-gray-300 bg-gray-100 px-8 py-4 text-lg hover:bg-gray-50 dark:border-gray-700 dark:bg-gray-800 dark:hover:border-gray-600 dark:hover:bg-gray-700"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
            viewBox="0 0 32 32"
            className="mr-4 h-5 w-5"
          >
            <defs>
              <path
                id="A"
                d="M44.5 20H24v8.5h11.8C34.7 33.9 30.1 37 24 37c-7.2 0-13-5.8-13-13s5.8-13 13-13c3.1 0 5.9 1.1 8.1 2.9l6.4-6.4C34.6 4.1 29.6 2 24 2 11.8 2 2 11.8 2 24s9.8 22 22 22c11 0 21-8 21-22 0-1.3-.2-2.7-.5-4z"
              />
            </defs>
            <clipPath id="B">
              <use xlinkHref="#A" />
            </clipPath>
            <g transform="matrix(.727273 0 0 .727273 -.954545 -1.45455)">
              <path d="M0 37V11l17 13z" clipPath="url(#B)" fill="#fbbc05" />
              <path
                d="M0 11l17 13 7-6.1L48 14V0H0z"
                clipPath="url(#B)"
                fill="#ea4335"
              />
              <path
                d="M0 37l30-23 7.9 1L48 0v48H0z"
                clipPath="url(#B)"
                fill="#34a853"
              />
              <path
                d="M48 48L17 24l-4-3 35-10z"
                clipPath="url(#B)"
                fill="#4285f4"
              />
            </g>
          </svg>
          <span>Sign In with Google</span>
        </button>
      </div>
    </div>
  );
};

export default Page;

// src/routes/auth/login/+page.svelte
<script>
	import { signIn } from '@auth/sveltekit/client';
</script>

<div class="w-full flex justify-center items-center">
	<div class="flex min-h-full items-center justify-center px-4 py-12 sm:px-6 lg:px-8">
		<div class="w-full max-w-sm space-y-10">
			<div>
				<img
					class="mx-auto h-10 w-auto"
					src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600"
					alt="Your Company"
				/>
				<h2 class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">
					Sign in to your account
				</h2>
			</div>
			<div class="relative -space-y-px rounded-md shadow-sm">
				<button
					on:click={() => signIn('google')}
					aria-label="Continue with google"
					class="focus:outline-none bg-white focus:ring-2 focus:ring-offset-1 focus:ring-gray-700 py-3.5 px-4 border rounded-lg border-gray-300 flex items-center w-full mt-10"
				>
					<svg
						width="19"
						height="20"
						viewBox="0 0 19 20"
						fill="none"
						xmlns="http://www.w3.org/2000/svg"
					>
						<path
							d="M18.9892 10.1871C18.9892 9.36767 18.9246 8.76973 18.7847 8.14966H9.68848V11.848H15.0277C14.9201 12.767 14.3388 14.1512 13.047 15.0812L13.0289 15.205L15.905 17.4969L16.1042 17.5173C17.9342 15.7789 18.9892 13.221 18.9892 10.1871Z"
							fill="#4285F4"
						/>
						<path
							d="M9.68813 19.9314C12.3039 19.9314 14.4999 19.0455 16.1039 17.5174L13.0467 15.0813C12.2286 15.6682 11.1306 16.0779 9.68813 16.0779C7.12612 16.0779 4.95165 14.3395 4.17651 11.9366L4.06289 11.9465L1.07231 14.3273L1.0332 14.4391C2.62638 17.6946 5.89889 19.9314 9.68813 19.9314Z"
							fill="#34A853"
						/>
						<path
							d="M4.17667 11.9366C3.97215 11.3165 3.85378 10.6521 3.85378 9.96562C3.85378 9.27905 3.97215 8.6147 4.16591 7.99463L4.1605 7.86257L1.13246 5.44363L1.03339 5.49211C0.37677 6.84302 0 8.36005 0 9.96562C0 11.5712 0.37677 13.0881 1.03339 14.4391L4.17667 11.9366Z"
							fill="#FBBC05"
						/>
						<path
							d="M9.68807 3.85336C11.5073 3.85336 12.7344 4.66168 13.4342 5.33718L16.1684 2.59107C14.4892 0.985496 12.3039 0 9.68807 0C5.89885 0 2.62637 2.23672 1.0332 5.49214L4.16573 7.99466C4.95162 5.59183 7.12608 3.85336 9.68807 3.85336Z"
							fill="#EB4335"
						/>
					</svg>
					<p class="text-base font-medium ml-4 text-gray-700">Continue with Google</p>
				</button>
			</div>
		</div>
	</div>
</div>
