// src/components/navbar.tsx
import { getCurrentUser } from "~/lib/session";
import { Icons } from "./icons";
import { ModeToggle } from "./mode-toggle";

type NavbarProps = {};

const Navbar = async (props: NavbarProps) => {
  const user = await getCurrentUser();

  return (
    <div className="fixed top-4 w-full px-4">
      <div className="dark:bg-gray-800/25 mx-auto flex min-w-min max-w-4xl items-center justify-between rounded-full border border-solid border-gray-200 bg-gray-100/25 px-4 py-2 backdrop-blur-md first-letter:w-full dark:border-gray-800">
        <div>
          <Icons.logo size={48} className="text-gray-700 dark:text-gray-300" />
        </div>
        <div className="flex items-center">
          <ul className="mr-3 flex">
            <li className="mx-3">
              <a
                href="/attendees"
                className="font-semibold text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-200"
              >
                Attendees
              </a>
            </li>
            <li className="mx-3">
              <a
                href={!user ? "/api/auth/signin/google" : "/api/auth/signout"}
                className="font-semibold text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-200"
              >
                {!user ? "Login" : "Logout"}
              </a>
            </li>
          </ul>
          <ModeToggle />
        </div>
      </div>
    </div>
  );
};

export default Navbar;

// src/lib/components/navbar.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { cn } from '$lib/utils/fn';
	import { Home, GraduationCap, Lock, Users } from 'lucide-svelte';

	let path: string;
	$: path = $page.url.pathname;
</script>

<nav
	class="flex-grow flex fixed bottom-0 lg:top-0 lg:bottom-auto w-full border-t lg:border-t-0 lg:border-b border-solid border-neutral-100 z-50"
>
	<ul class="flex w-full justify-around lg:justify-center py-4 bg-white">
		<li class="lg:mx-2">
			<a
				href="/"
				class={cn('block w-8 h-8 text-neutral-400 relative lg:w-auto lg:h-auto', {
					'text-red-400': path === '/'
				})}
			>
				<Home class="w-full h-full lg:hidden" />
				<p class="hidden lg:block lg:m-0">Home</p>
				{#if path === '/'}
					<div class="w-2 h-2 bg-red-400 rounded-full absolute -bottom-2 left-3 lg:hidden" />
				{/if}
			</a>
		</li>
		<li class="lg:mx-2">
			<a
				href="/graduates"
				class={cn('block w-8 h-8 text-neutral-400 relative lg:w-auto lg:h-auto', {
					'text-red-400': path === '/graduates'
				})}
			>
				<GraduationCap class="w-full h-full lg:hidden" />
				<p class="hidden lg:block lg:m-0">Graduates</p>
				{#if path === '/graduates'}
					<div class="w-2 h-2 bg-red-400 rounded-full absolute -bottom-2 left-3 lg:hidden" />
				{/if}
			</a>
		</li>
		{#if $page.data.session}
			<li class="lg:mx-2">
				<a
					href="/attendees"
					class={cn('block w-8 h-8 text-neutral-400 relative lg:w-auto lg:h-auto', {
						'text-red-400': path === '/attendees'
					})}
				>
					<Users class="w-full h-full lg:hidden" />
					<p class="hidden lg:block lg:m-0">Attendees</p>
					{#if path === '/attendees'}
						<div class="w-2 h-2 bg-red-400 rounded-full absolute -bottom-2 left-3 lg:hidden" />
					{/if}
				</a>
			</li>
			<li class="lg:mx-2">
				<a
					href="/admin"
					class={cn('block w-8 h-8 text-neutral-400 relative lg:w-auto lg:h-auto', {
						'text-red-400': path === '/admin'
					})}
				>
					<Lock class="w-full h-full lg:hidden" />
					<p class="hidden lg:block lg:m-0">Admin</p>
					{#if path === '/admin'}
						<div class="w-2 h-2 bg-red-400 rounded-full absolute -bottom-2 left-3 lg:hidden" />
					{/if}
				</a>
			</li>
		{/if}
		{#if $page.data.session}
			<li class="lg:mx-2">
				<a
					href="/auth/logout"
					class={cn('block w-8 h-8 text-neutral-400 relative lg:w-auto lg:h-auto', {
						'text-red-400': path === '/auth/logout'
					})}
				>
					<Lock class="w-full h-full lg:hidden" />
					<p class="hidden lg:block lg:m-0">Logout</p>
					{#if path === '/auth/logout'}
						<div class="w-2 h-2 bg-red-400 rounded-full absolute -bottom-2 left-3 lg:hidden" />
					{/if}
				</a>
			</li>
		{:else}
			<li class="lg:mx-2">
				<a
					href="/auth/login"
					class={cn('block w-8 h-8 text-neutral-400 relative lg:w-auto lg:h-auto', {
						'text-red-400': path === '/auth/login'
					})}
				>
					<Lock class="w-full h-full lg:hidden" />
					<p class="hidden lg:block lg:m-0">Login</p>
					{#if path === '/auth/login'}
						<div class="w-2 h-2 bg-red-400 rounded-full absolute -bottom-2 left-3 lg:hidden" />
					{/if}
				</a>
			</li>
		{/if}
	</ul>
</nav>
